export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';
export const SELECT_PROJECT_SUCCESS = 'SELECT_PROJECT_SUCCESS';

export const LOAD_CURRENT_USER_SUCCESS = 'LOAD_CURRENT_USER_SUCCESS';
export const LOAD_TOKENS_SUCCESS = 'LOAD_TOKENS_SUCCESS';
export const LOAD_DASHBOARD_SUCCESS = 'LOAD_DASHBOARD_SUCCESS';
export const REGISTER_NEW_USER = 'REGISTER_NEW_USER';
export const DROP_STORE = 'DROP_STORE';