export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const LOAD_NOTES_SUCCESS = 'LOAD_NOTES_SUCCESS';
export const LOAD_PROJECT_SUCCESS = 'LOAD_PROJECT_SUCCESS';
export const LOAD_TASKS_SUCCESS = 'LOAD_TASKS_SUCCESS';
export const LOAD_TASK_SUCCESS = 'LOAD_TASK_SUCCESS';
export const SELECT_PROJECT_SUCCESS = 'SELECT_PROJECT_SUCCESS';
export const UNLOAD_PROJECT = 'UNLOAD_PROJECT';


export const LOAD_CURRENT_USER_SUCCESS = 'LOAD_CURRENT_USER_SUCCESS';
export const LOAD_TOKENS_SUCCESS = 'LOAD_TOKENS_SUCCESS';
export const LOAD_DASHBOARD_SUCCESS = 'LOAD_DASHBOARD_SUCCESS';
export const REGISTER_NEW_USER = 'REGISTER_NEW_USER';
export const DROP_STORE = 'DROP_STORE';